In [7]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content' #path provided to upload the downloaded dataset

In [8]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets
License(s): MIT
Downloading walmart-10k-sales-datasets.zip to /content
  0% 0.00/143k [00:00<?, ?B/s]
100% 143k/143k [00:00<00:00, 65.4MB/s]

In [9]:
!unzip /content/walmart-10k-sales-datasets.zip

Archive:  /content/walmart-10k-sales-datasets.zip
  inflating: Walmart.csv

#### Data Exploration

In [10]:
import pandas as pd
print(pd.__version__)

2.2.2

In [11]:
df =pd.read_csv("/content/Walmart.csv")
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [12]:
df.shape

(10051, 11)

In [14]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [15]:
df.rename(columns={'unit_price': 'unit_price($)'}, inplace=True)
df.head(2)

,invoice_id,Branch,City,category,unit_price($),quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48

In [16]:
df['unit_price($)'] = df['unit_price($)'].str.replace('$', '').astype('float')

In [17]:
df.head(3)

,invoice_id,Branch,City,category,unit_price($),quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33

In [18]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price($)     float64
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [19]:
df.duplicated().sum() ##all duplicates

51

In [20]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

In [21]:
##droping missing values
df.dropna(inplace=True)
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price($)     0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [22]:
df.shape

(9969, 11)

In [23]:
## Adding a New column
df["Total Price"] = df["unit_price($)"]	* df["quantity"]

In [56]:
df.head(10)

,invoice_id,Branch,City,category,unit_price($),quantity,date,time,payment_method,rating,profit_margin,Total Price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17
5,6,WALM026,Denton,Electronic accessories,85.39,7.0,25/03/19,18:30:00,Ewallet,4.1,0.48,597.73
6,7,WALM088,Cleburne,Electronic accessories,68.84,6.0,25/02/19,14:36:00,Ewallet,5.8,0.33,413.04
7,8,WALM100,Canyon,Home and lifestyle,73.56,10.0,24/02/19,11:38:00,Ewallet,8.0,0.18,735.60
8,9,WALM066,Grapevine,Health and beauty,36.26,2.0,10/01/19,17:15:00,Credit card,7.2,0.33,72.52
9,10,WALM065,Texas City,Food and beverages,54.84,3.0,20/02/19,13:27:00,Credit card,5.9,0.33,164.52

In [55]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price($)     float64
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
Total Price       float64
dtype: object